[package]
name = "rust-marcos"
version = "0.1.0"
authors = ["hsl"]
license = "MIT"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
